### ISSUE TITLE
why using syscalls instead of implementing unsafe liburing ?

### ISSUE THREAD

**Issue by weinberggithub** [espoal/awesome-iouring#8]
Can you explain 'If you're doing Go/Rust, consider using syscalls instead of implementing unsafe liburing' in best.md please?

**Comment by espoal** [comment]
Here's the thing:

- Uring commands are very fast, because they don't require trepassing the kernel/userspace barrier which would cause a context switch. On the other hand, as you can see [here](https://github.com/espoal/uring_examples/blob/b1c1be5f32218d600f1f224441860656462f30b3/examples/nvme/src/main.rs#L34), they are very complex to get right and static tools like the rust borrow checker can't help you to find hidden bugs.
- Syscalls are very slow (2-3 order of magnitude slower), but it just requires a function call which hides for you the nasty details, allowing static analysis tools to help you

For time sensitive operations, like a read or a write, uring commands are for sure the way to go. Instead for one off operations, like setting up the ring or tearing down buffers, then a syscall becomes an interesting option.

Let me know if this answer your question @weinberggithub  :)

**Comment by weinberggithub** [comment]
> Here's the thing:
> 
> * Uring commands are very fast, because they don't require trepassing the kernel/userspace barrier which would cause a context switch. On the other hand, as you can see [here](https://github.com/espoal/uring_examples/blob/b1c1be5f32218d600f1f224441860656462f30b3/examples/nvme/src/main.rs#L34), they are very complex to get right and static tools like the rust borrow checker can't help you to find hidden bugs.
> * Syscalls are very slow (2-3 order of magnitude slower), but it just requires a function call which hides for you the nasty details, allowing static analysis tools to help you
> 
> For time sensitive operations, like a read or a write, uring commands are for sure the way to go. Instead for one off operations, like setting up the ring or tearing down buffers, then a syscall becomes an interesting option.
> 
> Let me know if this answer your question @weinberggithub :)

thanks,  It was very helpful!
